/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author brenno.lima
 */
public class Cadastro extends javax.swing.JInternalFrame {

    ConectaBanco conect = new ConectaBanco();//realiza a conexão com o banco de dados, variavel global   
    ResultSet rs;

    public Cadastro() {
        initComponents();
        conect.conexao();//Conexão com o banco de dados
        jRadioNome.setSelected(true);
        preencherTabela("Select *from pessoa order by nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonbuscacadastro = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jtmatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jtnome = new javax.swing.JTextField();
        jtdata = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcativar = new javax.swing.JCheckBox();
        jCheckBoxsenha = new javax.swing.JCheckBox();
        jCombo_turno = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bt_gravar = new javax.swing.JButton();
        bt_alterar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_incluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtablecadastro = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jtpesquisa = new javax.swing.JTextField();
        jRadioMatricula = new javax.swing.JRadioButton();
        jRadioNome = new javax.swing.JRadioButton();
        jRadioStatus = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioTurno = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastrar");
        setVisible(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jtmatricula.setEnabled(false);
        jPanel6.add(jtmatricula);
        jtmatricula.setBounds(10, 30, 90, 25);

        jLabel3.setText("Matricula:");
        jPanel6.add(jLabel3);
        jLabel3.setBounds(10, 10, 80, 14);

        jLabel8.setText("Senha:");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(120, 10, 60, 14);

        jPasswordField1.setEnabled(false);
        jPanel6.add(jPasswordField1);
        jPasswordField1.setBounds(120, 30, 90, 25);

        jLabel4.setText("Nome:");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(250, 10, 60, 14);

        jtnome.setEnabled(false);
        jtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtnomeKeyReleased(evt);
            }
        });
        jPanel6.add(jtnome);
        jtnome.setBounds(250, 30, 290, 25);

        jtdata.setEnabled(false);
        jPanel6.add(jtdata);
        jtdata.setBounds(180, 90, 100, 25);

        jLabel5.setText("Data Admissão:");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(180, 70, 110, 14);

        jcativar.setBackground(new java.awt.Color(255, 255, 255));
        jcativar.setForeground(new java.awt.Color(255, 0, 51));
        jcativar.setText("Desabilitar Estagiário");
        jcativar.setEnabled(false);
        jPanel6.add(jcativar);
        jcativar.setBounds(320, 90, 160, 23);

        jCheckBoxsenha.setEnabled(false);
        jCheckBoxsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxsenhaActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBoxsenha);
        jCheckBoxsenha.setBounds(210, 32, 20, 21);

        jCombo_turno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "MATUTINO", "VESPERTINO" }));
        jCombo_turno.setEnabled(false);
        jCombo_turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_turnoActionPerformed(evt);
            }
        });
        jPanel6.add(jCombo_turno);
        jCombo_turno.setBounds(10, 90, 120, 25);

        jLabel9.setText("Turno de Trabalho:");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(10, 70, 110, 14);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        bt_gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Grava_32x32.png"))); // NOI18N
        bt_gravar.setText(" - Gravar");
        bt_gravar.setEnabled(false);
        bt_gravar.setMaximumSize(new java.awt.Dimension(105, 41));
        bt_gravar.setMinimumSize(new java.awt.Dimension(105, 41));
        bt_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gravarActionPerformed(evt);
            }
        });
        jPanel4.add(bt_gravar);
        bt_gravar.setBounds(5, 48, 130, 40);

        bt_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Alterar_32x32.png"))); // NOI18N
        bt_alterar.setText(" - Alterar");
        bt_alterar.setEnabled(false);
        bt_alterar.setMaximumSize(new java.awt.Dimension(105, 41));
        bt_alterar.setMinimumSize(new java.awt.Dimension(105, 41));
        bt_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarActionPerformed(evt);
            }
        });
        jPanel4.add(bt_alterar);
        bt_alterar.setBounds(5, 90, 130, 40);

        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cancelar_32x32.png"))); // NOI18N
        bt_cancelar.setText(" - Cancelar");
        bt_cancelar.setEnabled(false);
        bt_cancelar.setMaximumSize(new java.awt.Dimension(105, 41));
        bt_cancelar.setMinimumSize(new java.awt.Dimension(105, 41));
        bt_cancelar.setPreferredSize(new java.awt.Dimension(111, 41));
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });
        jPanel4.add(bt_cancelar);
        bt_cancelar.setBounds(5, 133, 130, 41);

        bt_incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Incluir_32x32.png"))); // NOI18N
        bt_incluir.setText("- Incluir");
        bt_incluir.setToolTipText("");
        bt_incluir.setPreferredSize(new java.awt.Dimension(111, 41));
        bt_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_incluirActionPerformed(evt);
            }
        });
        jPanel4.add(bt_incluir);
        bt_incluir.setBounds(5, 5, 130, 41);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setToolTipText("");

        Jtablecadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Jtablecadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtablecadastroMouseClicked(evt);
            }
        });
        Jtablecadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtablecadastroKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Jtablecadastro);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtpesquisaActionPerformed(evt);
            }
        });
        jtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtpesquisaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtpesquisaKeyTyped(evt);
            }
        });

        buttonbuscacadastro.add(jRadioMatricula);
        jRadioMatricula.setText("Matricula");
        jRadioMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMatriculaActionPerformed(evt);
            }
        });

        buttonbuscacadastro.add(jRadioNome);
        jRadioNome.setText("Nome");
        jRadioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNomeActionPerformed(evt);
            }
        });

        buttonbuscacadastro.add(jRadioStatus);
        jRadioStatus.setText("Status");
        jRadioStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioStatusActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Localizar_16x16.png"))); // NOI18N
        jLabel7.setText("Buscar por nome:");

        buttonbuscacadastro.add(jRadioTurno);
        jRadioTurno.setText("Turno");
        jRadioTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTurnoActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("Ordenar Por:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jRadioMatricula)
                .addGap(56, 56, 56)
                .addComponent(jRadioNome)
                .addGap(56, 56, 56)
                .addComponent(jRadioStatus)
                .addGap(56, 56, 56)
                .addComponent(jRadioTurno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioMatricula)
                    .addComponent(jRadioNome)
                    .addComponent(jRadioStatus)
                    .addComponent(jRadioTurno)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 731, 537);
    }// </editor-fold>//GEN-END:initComponents

    private void jtnomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtnomeKeyReleased
        String temp = jtnome.getText();
        jtnome.setText(temp.toUpperCase());
    }//GEN-LAST:event_jtnomeKeyReleased

    private void jCheckBoxsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxsenhaActionPerformed
        if (jCheckBoxsenha.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);//mostrar senha
        } else {
            jPasswordField1.setEchoChar('*'); //ocultar senha
        }
    }//GEN-LAST:event_jCheckBoxsenhaActionPerformed
    private String formataData() {//função converte data
        String da = LocalDate.now().toString();//2018-05-21
        String ano = da.substring(0, 4);
        String mes = da.substring(5, 7);
        String dia = da.substring(8, 10);
        String datap = dia + "/" + mes + "/" + ano;
        return datap;
    }

    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Matricula", "Nome", "Data Admissão", "Status", "Turno"};
        conect.executaSQL(SQL);
        try {
            conect.rs.first();
            do {
                dados.add(new Object[]{conect.rs.getInt("Matricula"), conect.rs.getString("Nome"), conect.rs.getString("DataAdmissao"), conect.rs.getString("status"), conect.rs.getString("turno")});
            } while (conect.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não Lista na Tabela!\n Erro: " + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        Jtablecadastro.setModel(modelo);

        Jtablecadastro.getColumnModel().getColumn(0).setPreferredWidth(85);
        Jtablecadastro.getColumnModel().getColumn(0).setResizable(false);

        Jtablecadastro.getColumnModel().getColumn(1).setPreferredWidth(230);
        Jtablecadastro.getColumnModel().getColumn(1).setResizable(false);

        Jtablecadastro.getColumnModel().getColumn(2).setPreferredWidth(100);
        Jtablecadastro.getColumnModel().getColumn(2).setResizable(false);

        Jtablecadastro.getColumnModel().getColumn(3).setPreferredWidth(100);
        Jtablecadastro.getColumnModel().getColumn(3).setResizable(false);

        Jtablecadastro.getColumnModel().getColumn(4).setPreferredWidth(100);
        Jtablecadastro.getColumnModel().getColumn(4).setResizable(false);

        Jtablecadastro.getTableHeader().setReorderingAllowed(false);
        Jtablecadastro.setAutoResizeMode(Jtablecadastro.AUTO_RESIZE_OFF);
        Jtablecadastro.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    private void jCombo_turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_turnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombo_turnoActionPerformed

    private void jtpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtpesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtpesquisaActionPerformed

    private void jtpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpesquisaKeyReleased
        String temp = jtpesquisa.getText();
        jtpesquisa.setText(temp.toUpperCase());
        preencherTabela("Select *from pessoa where nome like '%" + jtpesquisa.getText() + "%'");
    }//GEN-LAST:event_jtpesquisaKeyReleased
    private void OrdenarTabela() {
        if (jRadioNome.isSelected()) {
            preencherTabela("Select *from pessoa order by nome");
        } else if (jRadioMatricula.isSelected()) {
            preencherTabela("Select *from pessoa order by matricula");
        } else if (jRadioStatus.isSelected()) {
            preencherTabela("Select *from pessoa order by status");
        } else if (jRadioTurno.isSelected()) {
            preencherTabela("Select *from pessoa order by turno");
        }
    }
    private void jtpesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpesquisaKeyTyped

    }//GEN-LAST:event_jtpesquisaKeyTyped
    public void buscaMatricula(String SQL) {//realiza um busca no banco de dados       
        conect.executaSQL(SQL);
        try {
            conect.rs.next();
            int matri;
            String dez;
            matri = conect.rs.getInt("MAX");
            dez = Integer.toString(matri + 1);//converte inteiro para string.
            jtmatricula.setText(dez);
        } catch (SQLException ex) {
            System.out.println("Erro ao Gerar Matricula \n" + ex);
        }
    }
    private void JtablecadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtablecadastroMouseClicked
        jPasswordField1.setEnabled(true);
        int linha = Jtablecadastro.getSelectedRow();
        jtmatricula.setText(Jtablecadastro.getValueAt(linha, 0).toString());
        String mt = Jtablecadastro.getValueAt(linha, 0).toString();//declara pára busca da senha
        jtnome.setText(Jtablecadastro.getValueAt(linha, 1).toString());
        jtdata.setText(Jtablecadastro.getValueAt(linha, 2).toString());
        String n = (Jtablecadastro.getValueAt(linha, 3).toString());
        String turno = (Jtablecadastro.getValueAt(linha, 4).toString());//hora entrada
        buscaSenha("select matricula, nome, senha from pessoa where matricula = '" + mt + "'");
        if ("MATUTINO".equals(turno)) {
            jCombo_turno.setSelectedIndex(1);
        } else {
            jCombo_turno.setSelectedIndex(2);
        }
        if ("DESATIVADO".equals(n)) {
            jcativar.setSelected(true);
        } else {
            jcativar.setSelected(false);
        }
        bt_alterar.setEnabled(true);
        bt_incluir.setEnabled(false);
        bt_cancelar.setEnabled(true);

        jtdata.setEnabled(true);
        jtmatricula.setEnabled(false);
        jtnome.setEnabled(true);
        jcativar.setEnabled(true);
        jCombo_turno.setEnabled(true);
        jCheckBoxsenha.setEnabled(true);
    }//GEN-LAST:event_JtablecadastroMouseClicked

    private void JtablecadastroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtablecadastroKeyReleased
        int linha = Jtablecadastro.getSelectedRow();
        jtmatricula.setText(Jtablecadastro.getValueAt(linha, 0).toString());
        String mt = Jtablecadastro.getValueAt(linha, 0).toString();//declara pára busca da senha
        jtnome.setText(Jtablecadastro.getValueAt(linha, 1).toString());
        jtdata.setText(Jtablecadastro.getValueAt(linha, 2).toString());
        String n = (Jtablecadastro.getValueAt(linha, 3).toString());
        String turno = (Jtablecadastro.getValueAt(linha, 4).toString());//hora entrada
        buscaSenha("select matricula, nome, senha from pessoa where matricula = '" + mt + "'");
        if ("MATUTINO".equals(turno)) {
            jCombo_turno.setSelectedIndex(1);
        } else {
            jCombo_turno.setSelectedIndex(2);
        }
        if ("DESATIVADO".equals(n)) {
            jcativar.setSelected(true);
        } else {
            jcativar.setSelected(false);
        }
    }//GEN-LAST:event_JtablecadastroKeyReleased

    private void bt_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gravarActionPerformed
        if (!jCombo_turno.getSelectedItem().equals("<SELECIONE>")) {
            try {
                PreparedStatement pst = conect.conn.prepareStatement("insert into pessoa(matricula,nome,dataadmissao,status, senha, turno) values(?,?,?,?,?,?)");
                int mt = Integer.parseInt(jtmatricula.getText().trim());//converter numero em String para inteiro.
                int senha = Integer.parseInt(jPasswordField1.getText().trim());//converter numero em String para inteiro.
                String situa;
                if (!jcativar.isSelected()) {
                    situa = "ATIVO";
                } else {
                    situa = "DESATIVADO";
                }
                pst.setInt(1, mt);
                pst.setString(2, jtnome.getText().trim());
                pst.setString(3, jtdata.getText().trim());
                pst.setString(4, situa.trim());
                pst.setInt(5, senha);
                pst.setString(6, jCombo_turno.getSelectedItem().toString());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Registro Salvo com Sucesso!!! ");
                preencherTabela("Select *from pessoa order by nome");
                jtdata.setEnabled(false);
                jtmatricula.setEnabled(false);
                jtnome.setEnabled(false);
                jcativar.setEnabled(false);
                bt_gravar.setEnabled(false);
                bt_alterar.setEnabled(true);
                bt_incluir.setEnabled(true);
                bt_cancelar.setEnabled(false);
                jCombo_turno.setEnabled(false);
                jCheckBoxsenha.setEnabled(false);

                jCheckBoxsenha.setEnabled(false);
                jtmatricula.setText("");
                jtnome.setText("");
                jPasswordField1.setText("");
                jtdata.setText("");
                jPasswordField1.setEnabled(false);
                jCheckBoxsenha.setSelected(false);
                jcativar.setSelected(false);
                jCombo_turno.setSelectedIndex(0);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro na Inserção!\n Erro: " + ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o Turno de Trabalho!!! ");
        }
    }//GEN-LAST:event_bt_gravarActionPerformed

    private void bt_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarActionPerformed
        bt_incluir.setEnabled(true);

        bt_alterar.setEnabled(false);
        bt_cancelar.setEnabled(false);
        jtdata.setEnabled(false);
        jtnome.setEnabled(false);
        jcativar.setEnabled(false);
        jCombo_turno.setEnabled(false);
        jCheckBoxsenha.setEnabled(false);
        jPasswordField1.setEnabled(false);
        if (!jCombo_turno.getSelectedItem().equals("<SELECIONE>")) {
            try {
                PreparedStatement pst = conect.conn.prepareStatement("update pessoa set nome=?,dataadmissao=?,status=?,senha=?, turno=? where matricula=?");
                pst.setString(1, jtnome.getText().trim());
                pst.setString(2, jtdata.getText().trim());
                String situa;
                if (!jcativar.isSelected()) {
                    situa = "ATIVO";
                } else {
                    situa = "DESATIVADO";
                }
                pst.setString(3, situa.trim());
                pst.setInt(4, Integer.parseInt(jPasswordField1.getText().trim()));
                pst.setString(5, jCombo_turno.getSelectedItem().toString());
                pst.setInt(6, Integer.parseInt(jtmatricula.getText().trim()));//converter numero em String para inteiro.
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Registro Alterado com Sucesso!!! ");
                preencherTabela("Select *from pessoa order by nome");
                jCheckBoxsenha.setEnabled(false);
                jtmatricula.setText("");
                jtnome.setText("");
                jPasswordField1.setText("");
                jtdata.setText("");
                jCheckBoxsenha.setSelected(false);
                jcativar.setSelected(false);
                jCombo_turno.setSelectedIndex(0);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro na Alteração do Registro!\n Erro: " + ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o Turno de Trabalho!!! ");
        }
        preencherTabela("Select *from pessoa order by nome");
    }//GEN-LAST:event_bt_alterarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        jtdata.setEnabled(false);
        jtmatricula.setEnabled(false);
        jtnome.setEnabled(false);
        jcativar.setEnabled(false);
        bt_gravar.setEnabled(false);
        bt_alterar.setEnabled(false);

        bt_incluir.setEnabled(true);
        bt_cancelar.setEnabled(false);
        jPasswordField1.setEnabled(false);
        jCombo_turno.setEnabled(false);

        jCheckBoxsenha.setEnabled(false);
        jtmatricula.setText("");
        jtnome.setText("");
        jPasswordField1.setText("");
        jtdata.setText("");
        jCheckBoxsenha.setSelected(false);
        jcativar.setSelected(false);
        jCombo_turno.setSelectedIndex(0);
    }//GEN-LAST:event_bt_cancelarActionPerformed
    public void buscaSenha(String SQL) {//realiza um busca no banco de dados       
        conect.executaSQL(SQL);
        try {
            conect.rs.next();
            int sen, matri;
            String nome, dez;
            matri = conect.rs.getInt("matricula");
            nome = conect.rs.getString("Nome");
            sen = conect.rs.getInt("senha");
            dez = Integer.toString(sen);//converte inteiro para string.
            jPasswordField1.setText(dez);
        } catch (SQLException ex) {
            System.out.println("Busca 'S' não encontrada!!! \n" + ex);
        }
    }
    private void bt_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_incluirActionPerformed
        jtdata.setEnabled(true);
        jtnome.setEnabled(true);
        jcativar.setEnabled(true);
        bt_gravar.setEnabled(true);
        bt_alterar.setEnabled(false);

        bt_incluir.setEnabled(false);
        bt_cancelar.setEnabled(true);
        jPasswordField1.setEnabled(true);
        jCombo_turno.setEnabled(true);
        jtmatricula.setText("");
        jtnome.setText("");
        jCheckBoxsenha.setEnabled(true);
        jtdata.setText(formataData()); //formataData e uma funcção que retorna String data
        buscaMatricula("Select Max(matricula) from pessoa");
    }//GEN-LAST:event_bt_incluirActionPerformed

    private void jRadioMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMatriculaActionPerformed
        OrdenarTabela();
    }//GEN-LAST:event_jRadioMatriculaActionPerformed

    private void jRadioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNomeActionPerformed
        OrdenarTabela();
    }//GEN-LAST:event_jRadioNomeActionPerformed

    private void jRadioStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioStatusActionPerformed
        OrdenarTabela();
    }//GEN-LAST:event_jRadioStatusActionPerformed

    private void jRadioTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTurnoActionPerformed
        OrdenarTabela();
    }//GEN-LAST:event_jRadioTurnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtablecadastro;
    private javax.swing.JButton bt_alterar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_gravar;
    private javax.swing.JButton bt_incluir;
    private javax.swing.ButtonGroup buttonbuscacadastro;
    private javax.swing.JCheckBox jCheckBoxsenha;
    private javax.swing.JComboBox<String> jCombo_turno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioMatricula;
    private javax.swing.JRadioButton jRadioNome;
    private javax.swing.JRadioButton jRadioStatus;
    private javax.swing.JRadioButton jRadioTurno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcativar;
    private javax.swing.JTextField jtdata;
    private javax.swing.JTextField jtmatricula;
    private javax.swing.JTextField jtnome;
    private javax.swing.JTextField jtpesquisa;
    // End of variables declaration//GEN-END:variables

}
